 [workspace]
 resolver = "2"
#  crates =[
#     "crates/*"
#  ]
members = ["crates/common","crates/engine", "crates/oms", "crates/utils/ringbuffer", "crates/instruments", "crates/shared-protos", "crates/transport", "crates/gateway", "crates/risk", "crates/markets"]

[workspace.dependencies]
rust_decimal_macros = "1.40.0"
rust_decimal = { version =  "1.40.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
uuid = { version = "1.20.0", features = ["v4", "serde"] }
socket2 = "0.6.2"
bincode2 = "2.0.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
thiserror = "2.0.18"
metrics = "0.24.3"
clap = { version =  "4.5.60", features = ["derive"] }
zerocopy = { version = "0.8.42", features = ["derive"] }
ctrlc = "3.5.2"
toml = "1.1.2"
dotenv = "0.15.0"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls", "macros", "migrate"] }
tokio ={ version = "1.50.0", features = ["full"] }
prost = "0.14.3"
tonic = "0.14.5" 
tonic-prost-build = "0.14.5"
tonic-prost = "0.14.5"
async-trait = "0.1.89"
rusteron-client ={ version = "0.1.163", features = ["static", "precompile"]  }
crossbeam-utils = "0.8.21"
rtrb = "0.3.4"
crossbeam = "0.8.4"