use common::{
    mem_pool::POOL_IDX_NULL,
    types::{
        CLIENT_ID_INVALID, ClientId, ORDER_ID_INVALID, OrderId, OrderSide, OrderType,
        PRICE_INVALID, PRIORITY_INVALID, PoolIdx, Price, Priority, QTY_INVALID, Qty,
        TICKER_ID_INVALID, TickerId,
    },
};
use zerocopy::{Immutable, IntoBytes, KnownLayout, TryFromBytes};

#[derive(Debug, IntoBytes, Immutable, KnownLayout, TryFromBytes, Clone, Copy)]
#[repr(C)]
pub struct Order {
    /// Represents the price of the order
    pub price: Price, // offset 0 aligmentb 16 bytes
    /// Represent the quantity of the order that is still active in the order book.
    pub quantity: Qty, // offset 16
    /// Represents the exact position of this order in the queue of other MEOrder instances with the same side_ and price_ values.”
    pub priority: Priority, // offset 32
    pub timestamp: u64, // offset 40
    /// Order ID generated from and sent by the client which owns the order
    pub client_order_id: OrderId, // offset 48
    /// Order ID generated by the matching engine and is unique across all clients.
    pub market_order_id: OrderId, // offset 56
    pub prev_order: PoolIdx, // offset 64
    pub next_order: PoolIdx, // offset 68
    /// Captures the market participant who owns this order.
    pub client_id: ClientId, // offset 72
    /// “TickerId to represent the instrument that this order corresponds to.”
    pub ticker_id: TickerId, // offset 76
    /// Represents whether the order is a buy or sell order.
    pub side: OrderSide, // offset 80
    pub order_type: OrderType, // offset 81
    _padding: [u8; 14], // offset 82 + padding(14 bytes) = 96 which is a multiple of 16
}

impl Default for Order {
    fn default() -> Self {
        Self {
            price: PRICE_INVALID,
            quantity: QTY_INVALID,
            priority: PRIORITY_INVALID,
            timestamp: 0, // REMOVE TIMESTAM
            client_order_id: ORDER_ID_INVALID,
            market_order_id: ORDER_ID_INVALID,
            prev_order: POOL_IDX_NULL,
            next_order: POOL_IDX_NULL,
            client_id: CLIENT_ID_INVALID,
            ticker_id: TICKER_ID_INVALID,
            side: OrderSide::Unset,
            order_type: OrderType::LIMIT, // remove this
            _padding: [0u8; 14],
        }
    }
}
